### ISSUE TITLE
[Supportplatform-Web] Show photo and login (on dropdown) of user logged (image on description of this issue)

### ISSUE THREAD

**Issue by Lucas-Angelo** [ICEI-PUC-Minas-PPLES-TI/plf-es-2023-1-tcci-0393100-dev-gitgrade#206]
![Image](https://github.com/ICEI-PUC-Minas-PPLES-TI/plf-es-2023-1-tcci-0393100-dev-plataformaapoioavaliacoesprojetos/assets/49598959/11900716-1e4f-464e-8057-94f239035eee)

**Comment by guizombas** [comment]
not trivial, and not valuable enough
