### ISSUE TITLE
Rename files

### ISSUE THREAD

**Issue by CleitonSilvaT** [ICEI-PUC-Minas-PPLES-TI/plf-es-2023-1-tcci-0393100-dev-gitgrade#28]
https://github.com/ICEI-PUC-Minas-PPLES-TI/plf-es-2023-1-tcci-0393100-dev-plataformaapoioavaliacoesprojetos/tree/master/Artefatos/Versoes/Prototipos/1

Atualizar o nome dos arquivos com a numeração das figuras seguidas no documento

**Comment by Lucas-Angelo** [comment]
> https://github.com/ICEI-PUC-Minas-PPLES-TI/plf-es-2023-1-tcci-0393100-dev-plataformaapoioavaliacoesprojetos/tree/master/Artefatos/Versoes/Prototipos/1
> 
> Atualizar o nome dos arquivos com a numeração das figuras seguidas no documento

@CleitonSilvaT atualizarei com a numeração atual, porém, não o nome do arquivo todo, apenas o início, pois, já que é uma das últimas seções do documento, a numeração continuará mudando...

**Comment by Lucas-Angelo** [comment]
@CleitonSilvaT https://github.com/ICEI-PUC-Minas-PPLES-TI/plf-es-2023-1-tcci-0393100-dev-plataformaapoioavaliacoesprojetos/commit/b5516067d543ff8a5572e7d9b606eed1be71c771
